#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#44475a"
bspc config focused_border_color "#44475a"
bspc config presel_feedback_color "#6272a4"
bspc wm -d | jq '.monitors[].rectangle'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Min desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a TelegramDesktop state=floating follow=on
bspc rule -a zoom state=floating follow=on
bspc rule -a Alacritty state=floating rectangle=800x500+100+100
bspc rule -a TelegramDesktop  state=floating 
bspc rule -a Pcmanfm state=floating follow=on rectangle=740x485+20+50
bspc rule -a code-oss  desktop='^3' state=floating follow=on rectangle=900x800+100+150
bspc rule -a Plank layer=above manage=on border=off
bspc rule -a Pavucontrol state=floating

#polybar
bash $HOME/.config/polybar/launch.sh --hack &
#background
feh --bg-scale ~/Pictures/adam-kool-ndN00KmbJ1c-unsplash.jpg &
dunst -conf ~/.config/dunst/dunstrc &
nm-applet &
## compositor
#picom -b --config $HOME/.config/picom.conf &

